### ISSUE TITLE
Allow users to lock an entire series from editing (rather than just individual games)

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/bowling-companion#121]
Request from user:

> ... a lock series button to just lock the whole thing and have an icon in the series bar that shows the whole series is locked and can't be changed?.

**Comment by joseph-roque** [comment]
Not entirely sure of how this will be implemented. Currently, the series bar is a bit cluttered and adding a lock to that will only worsen it. Putting this in the backlog to be potentially added later.
