### ISSUE TITLE
Add handicap to scores

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/bowling-companion#135]
Description from user:

> It is a flat value that is added to the score each game. It is based on the bowler's average and since the average changes overtime, the value will change from week to week. 
> I want to be able to record the pins and add the handicap to be the total score. That will, in turn, be considered in the stats.

**Comment by josephroqueca** [comment]
Some thoughts:
- Scoreboard would show frames, then10th frame, then final score with fouls + handicap applied
- Button could be below final score (Add Handicap)?
