### ISSUE TITLE
Create a test suite

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/bowling-companion#262]
The Bowling Companion app is sorely lacking a comprehensive test suite — or any test suite at all.

Core functionality should be focused on first: unit tests, integration tests, UI tests. From there, fringe features can start to be covered as well.

**Comment by josephroqueca** [comment]
Check out the following project for details on setting up the initial test suite:

https://github.com/josephroqueca/bowling-companion/projects/18
